site_name: Документация новостного бота
nav:
  - Главная: index.md
  - Руководство по установке: setup.md
  - Руководство по использованию:
      - Команды бота: usage/commands.md
      - Парсинг новостей: usage/parsing.md
  - База данных: database.md
theme:
  name: material

